name: Check pull requests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'
    types:
      - opened

jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    if: "(( github.event.pull_request.organization == 'exastro-suite') && ( github.event.pull_request.repository == 'exastro-it-automation-docs-dev'))"
    steps:
    - name: Check organization and repository
      run: echo "::error::Disallowed Request source branch"
