name: Check pull requests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'
    types:
      - opened

jobs:
  review_requested:
    dump:
      runs-on: ubuntu-latest
      steps:
        - name: dump context
          run: echo '${{ toJSON(github) }}'
    runs-on: ubuntu-latest
    if: "!(github.repository_owner == 'exastro-suite' \
        && github.repository == 'exastro-it-automation-docs' \
        && github.event.pull_request.base.user == 'exastro-suite' \
        && github.event.pull_request.base.repo == 'exastro-it-automation-docs-dev') \
        || github.event.pull_request.base.user != 'exastro-suite'"
    steps:
    - name: Check organization and repository
      run: |
        echo "::error::Disallowed Request source branch"
        exit 1
